### ISSUE TITLE
issue with unified, remark-slate-transformer and TS

### ISSUE THREAD

**Issue by julienfollow** [inokawa/remark-slate-transformer#101]
Hi
i have an issue with ur plugin, i don't know if come from your library or for unified. But with TS, i can't use this library ...
Idea ? I have same issue with stringify but i don't know why ... 
I use slate 0.47
Unified 9.2.1
Remark-stringify 9.0.0
And your librayry version 0.4.1 (just for try) but with last version i have error too 

Thanks !! 

![image](https://user-images.githubusercontent.com/70938205/163675105-1b4b6ded-797f-4a4a-a9c2-c622ddf1cc32.png)
![image](https://user-images.githubusercontent.com/70938205/163675118-c4ac4058-1557-4069-8fa6-e3b58e08655b.png)

**Comment by inokawa** [comment]
Currently this library is depending on types of unified 10.x.x.
So upgrading your unified and remark may solve the problem.

**Comment by julienfollow** [comment]
Hello @inokawa thanks a lot for your faster answer
It's ok with your library but i have still issue with strinigify
I go on her github to put my answer.
