### ISSUE TITLE
Issue with serialising images after update

### ISSUE THREAD

**Issue by siliconeidolon** [inokawa/remark-slate-transformer#181]
We're attempting to update to the latest version (0.9.0) along with Unified/Remark 11 and have an issue where adding an image as a sibling to other block level elements causes the markdown to lose its structure, with all elements appearing to be placed in a single paragraph.

eg: 
```js
// Slate with image
[
  {
    "type": "paragraph",
    "children": [ { "text": "first paragraph" }]
  },
  {
    "type": "paragraph",
    "children": [ { "text": "second paragraph" }]
  },
  {
    "type": "blockquote",
    "children": [
      {
        "type": "paragraph",
        "children": [ { "text": "quote" }]
      }
    ]
  },
  {
    "type": "image",
    "url": "https://i.imgur.com/ixnrvDU.png",
    "title": null,
    "alt": null,
    "children": [ { "text": "" }]
  }
]
// Serialised markdown
first paragraphsecond paragraph> quote![](https://i.imgur.com/ixnrvDU.png)
```

Here's a sandbox that shows the markdown conversion from a set of Slate nodes with and without images. Please have a look and let me know if I'm using the processor correctly:
https://codesandbox.io/p/sandbox/remark-slate-transformer-test-ydvggx?file=%2Fsrc%2Ftransformer.ts%3A6%2C1

In the version we were using previously (0.6.7), the block level element structure was retained.

Thanks for your work on this library.

**Comment by inokawa** [comment]
`Image` is a PhrasingContent in mdast(ast structure used in remark), that may suggest you should wrap them with a paragraph similar to other PhrasingContents like Strong/Emphasis/etc.
https://github.com/syntax-tree/mdast?tab=readme-ov-file#image

**Comment by siliconeidolon** [comment]
Thanks for the link - it clarifies why the change has happened. We landed on the paragraph solution and it's working. Since we treat images in our editor as blocks, I forgot that they're normally inline.

Interesting that the process has changed in the new version - previously when images were siblings of paragraphs, they were output on separate lines. Perhaps remark has changed to adhere more closely to the spec. I'll close this issue as it wasn't a problem with this library!
