### ISSUE TITLE
strikethrough (delete) not supported

### ISSUE THREAD

**Issue by jepser** [inokawa/remark-slate-transformer#4]
Hi @inokawa !
Thanks for the contribution, I was wondering how to add support to "strikethrough" , I'm quite new to how this works and I would like to add support to it, I see that "strikethrough" in mdast is called [Delete](https://github.com/syntax-tree/mdast#delete) which apparently should be supported by [remark-stringify](https://github.com/remarkjs/remark/blob/main/packages/remark-stringify/index.js) which is a wrapper for [mdast-to-markdown](https://github.com/syntax-tree/mdast-util-to-markdown/blob/main/lib/handle/index.js).

The last one doesn't support "delete", is there anyway that you can think of to support it?

**Comment by inokawa** [comment]
Hi @jepser . Thank you for considering my library!
This library supports `strike-through` already.
If you use `remark-parse` or `remark-stringify` and this with [remark-gfm](https://github.com/remarkjs/remark-gfm), you can convert `strike-through`.
If you have any questions, please ask me again.

**Comment by jepser** [comment]
Hey thanks for your super quick response, sorry if my question is basic but... how come would you do that? 

I have tried from let's say `~~this should be strike through~~`

```
const toRemark = unified()
  .use(slateToRemark)
  .use(stringify);

const tree = toRemark.runSync({
      type: 'root',
      children: astValue,
    });
    const stringifiedValue = toRemark.stringify(tree, {
      extensions: [gfm.toMarkdown()],
    });

```

also by removing `gfm.toMarkdown()` to the `toRemark` processor:

```
const toRemark = unified()
  .use(slateToRemark)
  .use(stringify, {
    extensions: [gfm.toMarkdown()],
  });
```
where `gfm` is: https://github.com/syntax-tree/mdast-util-gfm

Any ideas, it will so much be appreciated

**Comment by jepser** [comment]
Thanks for taking the time to answer!

No, the code is taken from an example, you're right with the format, the bold/italic/delete is set in the leaf. I will try with the code of the storybook (why I didn't think about that before 😅).

**Comment by jepser** [comment]
Interesting, it worked with `remark-gfm`, I really appreciate your help!

![](https://media.giphy.com/media/xULW8v7LtZrgcaGvC0/giphy.gif)
