### ISSUE TITLE
empty list item will crash slate

### ISSUE THREAD

**Issue by stefanprobst** [inokawa/remark-slate-transformer#42]
When converting markdown with an empty list item to slate ast, this will crash slate with "Cannot get the end point in the node at path [9,0] because it has no end text node."

**To reproduce**

1. Add an empty list item to the `article.md` fixture (see [here](https://github.com/inokawa/remark-slate-transformer/compare/master...stefanprobst:fix/emptychildren))
2. npm run storybook and see the crash

**Possible solution**

I'm not yet very familiar with slate, but it seems that guarding against empty `children` in `convertNodes` could work, see [here](https://github.com/inokawa/remark-slate-transformer/compare/master...stefanprobst:fix/empty-children).

Thanks!

**Comment by inokawa** [comment]
Hi, thank you for the report.

As described [here](https://docs.slatejs.org/concepts/10-normalizing#built-in-constraints), slate requires at least one Text descendant.
So I think your suggestion works and I'll fix it soon.

**Comment by stefanprobst** [comment]
thanks for the super quick fix!

**Comment by inokawa** [comment]
@stefanprobst 
Pubished in 0.3.0. Thanks!
