### ISSUE TITLE
Extra paragraph Node in listItems

### ISSUE THREAD

**Issue by jepser** [inokawa/remark-slate-transformer#5]
Hi! I have a rich editor which allows users to add lists with a markdown shortcut as per [this example](https://www.slatejs.org/examples/markdown-shortcuts).

I have checked that from markdown directly the list it renders correctly to slate. The issue comes when you want to edit within the slate editor adding more items after having a list as an initial value; it adds an extra paragraph Node, making the "enter to add a listItem" broken.

Here the loom 📹 : https://www.loom.com/share/dc5c5376d1e04bb8b11750692468e117

```
* hola
* adios
```

It should be like this:
```
[
  {
    "type": "list",
    "children": [
      {
        "type": "listItem",
        "children": [
          {
            "text": "hola"
          }
        ]
      },
      {
        "type": "listItem",
        "children": [
          {
            "text": "adios"
          }
        ]
      }
    ]
  }
]
```

but instead it renders this:

```
[
  {
    "type": "list",
    "children": [
      {
        "type": "listItem",
        "children": [
          {
            "type": "paragraph",
            "children": [
              {
                "text": "hola"
              }
            ]
          }
        ],
        "checked": null,
        "spread": false
      },
      {
        "type": "listItem",
        "children": [
          {
            "type": "paragraph",
            "children": [
              {
                "text": "adios"
              }
            ]
          }
        ],
        "checked": null,
        "spread": false
      }
    ],
    "ordered": false,
    "start": null,
    "spread": false
  }
]
```

See the extra:
```
{
  "type": "paragraph",
  "children": [
    {
      "text": "adios"
    }
  ]
}
```

The issue is when it comes from remarkToSlate

**Comment by inokawa** [comment]
Hi.
I guess the extra paragraph will be exported even if the listItem is single line like 

```
* hola
```

In [mdast](https://github.com/syntax-tree/mdast) (syntax tree used in remark internally), the structure of List is `List -> ListItem -> Paragraph -> Text`.
And this remarkToSlate also follow the structure, so extra paragraph appears.

However, list constructed with `ul`/`ol`/`li` in HTML doesn't have `p` usually.
So remove paragraph under ListItem might be better to use in slate...

**Comment by inokawa** [comment]
@jepser 
You seems to have solved the problem at https://github.com/remarkjs/remark/issues/563 .
So I close this issue.
