### ISSUE TITLE
Slate => Markdown not working correctly

### ISSUE THREAD

**Issue by palerdot** [inokawa/remark-slate-transformer#67]
`slate` version: `0.63.0`
`slate-react`: `0.65.2`

Following slate input is not correctly transformed to `markdown`

```
[
  {
    type: "paragraph",
    children: [
      {
        text: "Hello slate ",
      },
    ],
  },
  {
    type: "paragraph",
    children: [
      {
        text: "",
      },
    ],
  },
  {
    type: "blockquote",
    children: [
      {
        text: "Anything after this is not transformed ",
      },
    ],
  },
  {
    type: "p",
    children: [
      {
        text: "",
        code: true,
      },
    ],
  },
  {
    type: "p",
    children: [
      {
        code: true,
        text: "I'm not in the output",
      },
    ],
  },
  {
    type: "p",
    children: [
      {
        code: true,
        text: "",
      },
    ],
  },
  {
    type: "p",
    children: [
      {
        code: true,
        text: "Not in the output too",
      },
    ],
  },
  {
    type: "p",
    children: [
      {
        text: "I'm ignored",
      },
    ],
  },
]
```
Current Output
```
Hello slate 


> Anything after this is not transformed 

// subsequent elements are missing
```
In the above slate tree, anything after second blockquote does not appear in the final markdown.

**Comment by inokawa** [comment]
Hi @palerdot ,
Currently this library only output types listed in [mdast specification](https://github.com/syntax-tree/mdast).
Adding option to handle custom type is suggested several times (#31 #37) but not implemented yet because I don't have time (PRs are welcomed).

**Comment by palerdot** [comment]
Since the project's name has `remark` and `slate`, the default assumption is it would convert Slate trees to `markdown` out of the box. It seems it is not the case.

Thanks for the clarification.

**Comment by inokawa** [comment]
Close for now. If you have something feel free to reopen or create an issue.
