### ISSUE TITLE
Empty new lines are lost when converting to MD

### ISSUE THREAD

**Issue by moretti** [inokawa/remark-slate-transformer#68]
Hi @inokawa, just wondering if you are aware of this problem:

https://codesandbox.io/s/remark-slate-transformer-bffpe

I'm essentially trying to serialise the AST to markdown and store it as string, but noticed that new lines are lost during the serialisation/deserialisation process.

I noticed that for example other implementations, such as https://github.com/hanford/remark-slate, add some `<br>` tags to preserve them: https://github.com/hanford/remark-slate/blob/c17259600c1939bd85a338f77e5a3ac8906af767/src/deserialize.ts#L137-L144 🤔

**Comment by AndrejGajdos** [comment]
@inokawa is there a solution so fix this?
