### ISSUE TITLE
Combination of bold and italic at the start of a block losing formatting

### ISSUE THREAD

**Issue by siliconeidolon** [inokawa/remark-slate-transformer#90]
Here's a basic codesandbox example: https://codesandbox.io/s/bold-and-italic-y68d4?file=/src/App.tsx

Given a slate object in this shape:
```
[
  {
    "type": "paragraph",
    "children": [
      {
        "text": "Italic",
        "strong": true,
        "emphasis": true
      },
      {
        "strong": true,
        "text": " in a bold paragraph"
      }
    ]
  }
]
```
I'd expect to see it render like:
**_Italic_ in a bold paragraph**

The processed markdown looks like this:
`***Italic***** in a bold paragraph**`

And when it's read back into Slate, it renders like this:
_**Italic**_** in a bold paragraph**

It seems that the wrapping **s for bold are being lost for the second part of the text. 

In the second paragraph in the codesandbox, you can see that the same issue doesn't occur when the italic isn't at the start of the block, probably because the marks are separated.

I'm not sure if the issue is with this library, how my slate object is structured, or how remark treats marks. 

Let me know if you have any ideas for why this might be happening and thanks as always for maintaining this transformer - it has been very useful.

**Comment by inokawa** [comment]
The mdast tree of the output of `slateToRemark` plugin looks like below.

```json
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "emphasis",
          "children": [
            {
              "type": "strong",
              "children": [
                {
                  "type": "text",
                  "value": "Italic"
                }
              ]
            }
          ]
        },
        {
          "type": "strong",
          "children": [
            {
              "type": "text",
              "value": " in a bold paragraph"
            }
          ]
        }
      ]
    }
  ]
}

```

If the emphasis node and the child strong node were exchanged, the stringified markdown is correct so this would be a problem of this library.

**Comment by inokawa** [comment]
I added a hotfix in `0.6.7` but this may have sideeffects I'm not sure.
Feel free to reopen this issue if you have some problems.
